#!/usr/bin/env bash

set -o errexit
set -o xtrace

[[ $INSTALL_DEST ]]
[[ $VERSION ]]

sudo env PYTHON_BUILD_ROOT=/opt/pyenv/plugins/python-build \
  /opt/pyenv/plugins/python-build/bin/python-build $VERSION $INSTALL_DEST/$VERSION

if [[ $ALIAS ]] ; then
  sudo ln -s $INSTALL_DEST/$VERSION $INSTALL_DEST/$ALIAS
fi

virtualenv --distribute --python=$INSTALL_DEST/$VERSION/bin/python \
  /home/travis/virtualenv/python$VERSION

if [[ $ALIAS ]] ; then
  ln -s $HOME/virtualenv/python$VERSION $HOME/virtualenv/python$ALIAS
fi

if [[ $PACKAGES ]] ; then
  $HOME/virtualenv/python$VERSION/bin/pip install --upgrade $PACKAGES
fi
