#!/usr/bin/env bash

set -o errexit

if [[ ! $LSB_RELEASE ]] ; then
  echo 'Missing LSB_RELEASE'
  exit 1
fi

if [[ ! $INSTALL_DEST ]] ; then
  echo 'Missing INSTALL_DEST'
  exit 1
fi

if [[ ! $VERSION ]] ; then
  echo 'Missing VERSION'
  exit 1
fi

set -o xtrace

: ${TAR_PATHS:=}
: ${DEST:=${1}}

TAR_PATHS="$TAR_PATHS $INSTALL_DEST/$VERSION $HOME/virtualenv/python$VERSION"

if [[ $ALIAS ]] ; then
  TAR_PATHS="$TAR_PATHS $INSTALL_DEST/$ALIAS $HOME/virtualenv/python$ALIAS"
  DEST="$TRAVIS_BUILD_DIR/$LSB_RELEASE/python-${ALIAS}.tar.bz2"
else
  if [[ ! $DEST ]] ; then
    DEST="$TRAVIS_BUILD_DIR/$LSB_RELEASE/python-${VERSION}.tar.bz2"
  fi
fi

mkdir -p $(dirname $DEST)
tar -cjf $DEST $TAR_PATHS

echo "---> $DEST"
